title: BCBB Training Seminars at Rocky Mountain Labs
theme: jekyll-theme-minimal
repository: niaid/RML
destination: docs
url: "https://niaid.github.io"
baseurl: "/RML"

exclude: [.gitignore, Gemfile, README.md, bashrc]

plugins:
  - jekyll-github-metadata

permalinks: pretty


