title: BCBB Training Seminars at Rocky Mountain Labs
theme: jekyll-theme-minimal
repository: niaid/RML
destination: docs
url: "https://niaid.github.io/RML"

exclude: [.gitignore, Gemfile, README.md, _config.yml, docs.config.yml]

plugins:
  - jekyll-github-metadata

permalinks: pretty


