name: Jekyll site CI

on:
  push:
    branches:
      - action

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.JEKYLL_PAT }}
        ref: gh-pages
    - run: |
        git checkout gh-pages
        echo "yes" >>README.md
        git config user.name pooranibcbb
        git config user.email poorani.subramanian@nih.gov
        git config --global url."https://api:$GITHUB_TOKEN@github.com/".insteadOf "https://github.com/"
        git status
        git commit -a -m 'test commit'
        git status
        git push --dry-run origin gh-pages
      env:
        github_token: ${{ secrets.JEKYLL_PAT }}
