name: Jekyll site CI

on:
  push:
    branches:
      - action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.JEKYLL_PAT }}
        ref: gh-pages
        fetch-depth: 1
    - name: build
      env:
        github_token: ${{ secrets.JEKYLL_PAT }}
      run: |
        pwd
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "poorani.subramanian@nih.gov"
        git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}"
        git config -l
        git status
        echo "yes" >>README.md
        git commit -a -m 'update readme'
        git status
        git push --dry-run --verbose origin gh-pages
