name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site
      run: |
        bundle update
        bundle install
        rm -rf ./docs
        mkdir ./docs
        bundle exec jekyll build --future
        git add --all
        git commit -a -m 'update site'
        git push origin/master
