name: Jekyll site CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.JEKYLL_PAT }}
    - run: |
      name: bundle update
        git checkout master
        bundle update
        bundle install
    - run:
      name: jekyll build
        rm -rf ./docs
        mkdir ./docs
        bundle exec jekyll build --future
    - run:
      name: git push
        git add --all
        git commit -a -m 'update site'
        git push origin/master
