name: Jekyll site CI

on:
  push:
    branches:
      - action

jobs:
  build:
    runs-on: macos-latest

    steps:
      - env:
          github_token: ${{ secrets.JEKYLL_PAT }}
        run: |
          git config --global url."https://api:$GITHUB_TOKEN@github.com/".insteadOf "https://github.com/"
          git clone https://github.com/niaid/RML.git
          cd RML
	  git checkout gh-pages
          echo "yes" >>README.md
          git status
          git commit -a -m 'test commit'
          git status
          git push --dry-run origin gh-pages
