name: Jekyll site CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.JEKYLL_PAT }}
    - run: |
        git checkout master
        bundle update
        bundle install
        rm -rf ./docs
        mkdir ./docs
        cp docs.config.yml ./docs/_config.yml
        bundle exec jekyll build --future
        git add --all
        git commit -a -m 'update site'
        git push
