name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site
      run: |
        bundle update
        bundle install
        bundle exec jekyll build --future
