name: Jekyll site CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.JEKYLL_PAT }}
        ref: master
    - run: |
        git status
