name: Jekyll site CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.JEKYLL_PAT }}
	ref: master
    - run: |
        bundle update
        bundle install
        rm -rf ./docs
        mkdir ./docs
        bundle exec jekyll build --future
	cp docs.config.yml ./docs/_config.yml
	git config user.name pooranibcbb
	git config user.email poorani.subramanian@nih.gov
        git add --all
        git commit -a -m 'update site'
        git push
